title: Prerak Bhavsar
description: Experienced Legal Assistant | Paralegal | Law Clerk | Immigration Specialist | Committed to Excellence in Legal Services
#show_downloads: false
theme: jekyll-theme-slate
